### ISSUE TITLE
oft-sar-S1-GRD-MT-bulk-preprocess

### ISSUE THREAD

**Issue by HKCaesar** [openforis/opensarkit#2]
it seam that there is something wrong with it A=at line 123! it does not work to change dir to a zip file.

**Comment by BuddyVolly** [comment]
Dear HKCaesar,

Sorry, but I just saw your comment now. First of all let me say that I did some major changes with the last push. It will be probably the best to install all again, since the names of the command line commands changed. Sorry for that. 

However, the now called ost_S1_grd2rtc_bulk is only for bulk processing (and therefore only accepts the project directory created by the download routine). You should use the ost_S1_grd2rtc (old oft-sar-S1-GRD-preprocess) instead.

Please note, that we will very soon produce a fixed release that you can refer to, so you do not have to deal with my intermediate edits. 

Do not hesitate to contact me in case of other problems,
Best regards

**Comment by HKCaesar** [comment]
Thanks! I have try to update the scripts! I want to know the use :[oft-sar-S1-GRD-bulk-preprocess <input directory> <output resolution> <mode> <ts-processing>]   --paras--input directory [files tree structs  ?]. You know , as general. I have download some GRD products( such as S1A_IW_GRDH_1SDV_20150823T101314_20150823T101339_007389_00A295_07A5.zip ) . That is  : how to configure the input directory manually?

**Comment by BuddyVolly** [comment]
Hi, 

the download script actually creates a folder DATA within your project directory (i.e. /path/to/project/folder/DATA/). 

A first level subfolder refers to the different tracks (i.e. /path/to/project/folder/DATA/123A). If you don't know them, you can use artificial ones, important that they start with a number.

A second level subfolder is created by the acquisition date and track name (i.e. /path/to/project/folder/DATA/123A/20160101-123A). Again, important that those folders start at least with 201

If you have more than a coupe of consecutive frames per track and acquisition date (i.e. the products are from the same take), just put them inside the same 2nd level subfolder. The script will automatically detect and apply what is called swath assembly in SNAP. 

The final bulk processing command is then:

ost_S1_grd2rtc_bulk /path/to/project/folder/DATA/ MED_RES 1 1

This will create you also the Timeseries and Timescan products.

Hope that helps!
